name = "template_name"
version = "1.0.0"
type = "text"
production_host = "fuchsia-manatee-katee-cyezlwma.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build_release]
dir = "build"
entry = "template_name.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeif5nnbdgzii6xpgtp2mpu7ec3eclyylpnplpkoz27bjutnwitou7u"
created = "2025-07-22T19:28:14.335Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "e1bbd6cb582b6d2f3dc95dbb061a7a72ca5fc8946118d78b9df4cff6cec38781"
